version: 2
updates:
# Fetch and update latest `npm` packages
- package-ecosystem: npm
  directory: '/'
  schedule:
    interval: daily
    time: '00:00'
  open-pull-requests-limit: 10
  reviewers:
    - luatiq
  assignees:
    - luatiq
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
  ignore:
    - dependency-name: "vue-tabler-icons"
      versions: ["2.x"]
